name: fltter_inherited_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Simple Examples
  counter_example:
    path: ./examples/simple_level_examples/counter_example
  background_color_example:
    path: ./examples/simple_level_examples/background_color_example
  form_example:
    path: ./examples/simple_level_examples/form_example


  ## Medium Examples
  cat_app:
    path: ./examples/medium_level_examples/cat_app


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
